services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fishsense_data_processing_worker
    volumes:
      - fishsense_data_reef:/mnt/fishsense_data_reef:ro
      - ./settings.toml:/e4efs/config/settings.toml:ro
      - ./data:/e4efs/data:rw
      - ./logs:/e4efs/logs:rw
      - ./cache:/e4efs/cache:rw
      # - ./.secrets.toml:/.secrets.toml:ro
    environment:
    ports:
    secrets:
    deploy:
      resources:
        limits:
          memory: 4G


secrets:

volumes:
  fishsense_data_reef:
   external: true