apiVersion: apps/v1
kind: Deployment
metadata:
  name: fishsense-data-processing-worker
  labels:
    app: fishsense-data-processing-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fishsense-data-processing-worker
  template:
    metadata:
      labels:
        app: fishsense-data-processing-worker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/cuda.runtime.major
                operator: In
                values:
                - "12"
              - key: nvidia.com/cuda.runtime.minor
                operator: In
                values:
                - "6"
      containers:
        - name: fishsense-data-processing-worker
          image: ghcr.io/ucsd-e4e/fishsense-data-processing-worker:v0.4.0
          imagePullPolicy: Always
          env:
            - name: E4EFS_CORE__ORCHESTRATOR
              value: https://orchestrator.fishsense.e4e.ucsd.edu
            - name: E4EFS_CORE__API_KEY
              valueFrom:
                secretKeyRef:
                  name: fishense-data-processing-worker-orchestrator-api-key
                  key: api-key
            - name: E4EFS_CORE__WORKER_NAME
              value: nrp-worker
            - name: E4EFS_CORE__MAX_CPU
              value: "4"
            - name: E4EFS_CORE__MAX_GPU
              value: "1"
            - name: E4EFS_CORE__MAX_BATCH_SIZE
              value: "100"
          resources:
            limits:
              nvidia.com/gpu: 1
              cpu: 4
              memory: 32G
            requests:
              nvidia.com/gpu: 1
              cpu: 4
              memory: 32G