[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "fishsense_data_processing_worker"
version = "1.0.0"
description = "Fishsense Data Processing Worker"
authors = [
    "UCSD Engineers for Exploration <e4e@ucsd.edu>"
]
license = "UCSD"
readme = "README.md"
repository = 'https://github.com/UCSD-E4E/fishsense-data-processing-worker'

[tool.poetry.dependencies]
python = "^3.12"
dynaconf = "^3.2.10"
prometheus-client = "^0.21.1"
humanfriendly = "^10.0"
platformdirs = "^4.3.6"
schema = "^0.7.7"
pycron = "^3.1.2"
requests = "^2.32.4"

[tool.poetry.group.dev.dependencies]
pylint = "^3.2.7"
pytest = "^8.3.2"
jupyter = "^1.1.1"
autopep8 = "^2.3.1"
coverage = "^7.6.1"

[tool.poetry.scripts]
fsl_worker = 'fishsense_data_processing_worker.service:main'

[tool.semantic_release]
version_variables = ["fishsense_data_processing_worker/__init__.py:__version__"]
version_toml = [
    "pyproject.toml:tool.poetry.version",
]
assets = []
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
commit_parser = "conventional"
logging_use_named_masks = false
major_on_zero = true
tag_format = "v{version}"

[tool.semantic_release.branches.main]
match = "(main)"
prerelease = false
prerelease_token = "rc"

[tool.semantic_release.changelog]
template_dir = "templates"
changelog_file = "CHANGELOG.md"
exclude_commit_patterns = []

[tool.semantic_release.changelog.environment]
block_start_string = "{%"
block_end_string = "%}"
variable_start_string = "{{"
variable_end_string = "}}"
comment_start_string = "{#"
comment_end_string = "#}"
trim_blocks = false
lstrip_blocks = false
newline_sequence = "\n"
keep_trailing_newline = false
extensions = []
autoescape = true

[tool.semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "semantic-release <semantic-release>"

[tool.semantic_release.commit_parser_options]
allowed_tags = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "style", "refactor", "test"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]

[tool.semantic_release.remote]
name = "origin"
type = "github"
ignore_token_for_push = false

[tool.semantic_release.remote.token]
env = "GH_TOKEN"

[tool.semantic_release.publish]
dist_glob_patterns = ["dist/*"]
upload_to_vcs_release = true